# Project Group - 20

Members: 
1) Savino Every
2) Nicholas Johnson
3) Gijs van Vliet
4) Dániel Seesink
5) Delano van den Bosch


Student numbers: 

1) 6554741
2) 6798373
3) 4892747 
4) 6815014
5) 6127444

# Research Objective

*Requires data modeling and quantitative research in Transport, Infrastructure & Logistics*

# Contribution Statement

*Be specific. Some of the tasks can be coding (expect everyone to do this), background research, conceptualisation, visualisation, data analysis, data modelling*

**Author 1**:

**Author 2**:

**Author 3**:

## Imports

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
# import geopandas
import seaborn as sns

# Data Used

#### Traindata

In [30]:
train = pd.read_csv('traindata_selected.csv')
train = train.drop(columns = ['index', 'Service:Date', 'Service:RDT-ID',
                              'Stop:RDT-ID', 'Stop:Station code', 'Stop:Station name'])

cols = ['Stop:Arrival time', 'Stop:Departure time']

train[cols] = train[cols].apply(
    lambda col: pd.to_datetime(col).dt.strftime('%H:%M')
)
train.head()

,Service:Type,Service:Company,Service:Train number,Service:Completely cancelled,Service:Partly cancelled,Service:Maximum delay,Stop:Arrival time,Stop:Arrival delay,Stop:Arrival cancelled,Stop:Departure time,Stop:Departure delay,Stop:Departure cancelled,Stop:Platform change,Stop:Planned platform,Stop:Actual platform
0,Intercity,NS,1410,False,False,0,03:50,0.0,False,NaN,NaN,NaN,False,15.0,15.0
1,Intercity,NS,1409,False,False,1,NaN,NaN,NaN,02:15,0.0,False,False,7.0,7.0
2,Intercity,NS,1414,False,False,0,04:50,0.0,False,NaN,NaN,NaN,False,15.0,15.0
3,Intercity,NS,1413,False,False,3,NaN,NaN,NaN,03:15,3.0,False,True,7.0,5.0
4,Nightjet,NS Int,402,False,False,0,08:52,0.0,False,08:55,0.0,False,False,14.0,14.0

Keeping service type and company for analysis of sleeper trains for example

#### Weather data

In [6]:
weather = pd.read_csv('weather_selected.csv')
weather.head()

,# STN,YYYYMMDD,HH,DD,FH,FF,FX,T,T10N,TD,...,VV,N,U,WW,IX,M,R,S,O,Y
0,260,20260101,1,250,40,40,90,44,NaN,10,...,50,8.0,78,NaN,NaN,0,0,0,0,0
1,260,20260101,2,240,50,50,90,45,NaN,7,...,65,8.0,76,NaN,NaN,0,0,0,0,0
2,260,20260101,3,240,50,50,100,45,NaN,5,...,80,8.0,75,NaN,NaN,0,0,0,0,0
3,260,20260101,4,240,50,50,100,43,NaN,5,...,82,8.0,76,NaN,NaN,0,0,0,0,0
4,260,20260101,5,240,60,60,110,45,NaN,4,...,82,8.0,74,NaN,NaN,0,0,0,0,0

# Data Pipeline