# Data Used

#### Traindata

Only importing trains arriving and departing Utrecht Centraal for this initial analysis. Possible expansion to identify its origins or destinations or trajectories, but not in the dataset itself (need to check route manually).
- Possibility to check if primary delay or secondary delay!

Only selected columns which are unique to a train number to the station:
- Keeping train number for identification and service type for analysis of specific train types.

In [78]:
train = pd.read_csv('traindata_selected.csv')
train = train.drop(columns = ['index', 'Service:RDT-ID',
                              'Stop:RDT-ID', 'Stop:Station code', 'Stop:Station name'])
cols = ['Stop:Arrival time', 'Stop:Departure time']

train[cols] = train[cols].apply(
    lambda col: pd.to_datetime(col).dt.strftime('%H:%M')
)
train.head()

,Service:Date,Service:Type,Service:Company,Service:Train number,Service:Completely cancelled,Service:Partly cancelled,Service:Maximum delay,Stop:Arrival time,Stop:Arrival delay,Stop:Arrival cancelled,Stop:Departure time,Stop:Departure delay,Stop:Departure cancelled,Stop:Platform change,Stop:Planned platform,Stop:Actual platform
0,2026-01-01,Intercity,NS,1410,False,False,0,03:50,0.0,False,NaN,NaN,NaN,False,15.0,15.0
1,2026-01-01,Intercity,NS,1409,False,False,1,NaN,NaN,NaN,02:15,0.0,False,False,7.0,7.0
2,2026-01-01,Intercity,NS,1414,False,False,0,04:50,0.0,False,NaN,NaN,NaN,False,15.0,15.0
3,2026-01-01,Intercity,NS,1413,False,False,3,NaN,NaN,NaN,03:15,3.0,False,True,7.0,5.0
4,2026-01-01,Nightjet,NS Int,402,False,False,0,08:52,0.0,False,08:55,0.0,False,False,14.0,14.0

In [79]:
train['Service:Date'] = pd.to_datetime(train['Service:Date'])

counts_per_day = (
    train.groupby('Service:Date')
    .size()
    .reset_index(name='count')
)

counts_per_day['Weekday'] = counts_per_day['Service:Date'].dt.day_name()

In [80]:
train_disrupted = train[train['Service:Date'] == '2026-01-06']
train_disrupted = train_disrupted.drop_duplicates().reset_index(drop=True)
cancelled_train_arr = train_disrupted[train_disrupted['Stop:Arrival cancelled'] == True]
cancelled_train_dep = train_disrupted[train_disrupted['Stop:Departure cancelled'] == True]

In [81]:
train_disrupted

,Service:Date,Service:Type,Service:Company,Service:Train number,Service:Completely cancelled,Service:Partly cancelled,Service:Maximum delay,Stop:Arrival time,Stop:Arrival delay,Stop:Arrival cancelled,Stop:Departure time,Stop:Departure delay,Stop:Departure cancelled,Stop:Platform change,Stop:Planned platform,Stop:Actual platform
0,2026-01-06,Intercity,NS,1410,False,True,0,03:48,0.0,False,NaN,NaN,NaN,False,15.0,15.0
1,2026-01-06,Intercity,NS,1409,False,True,17,NaN,NaN,NaN,02:16,6.0,False,False,18.0,18.0
2,2026-01-06,Intercity,NS,1414,False,True,0,04:48,0.0,False,NaN,NaN,NaN,False,19.0,19.0
3,2026-01-06,Intercity,NS,1413,False,True,3,NaN,NaN,NaN,03:16,1.0,False,True,18.0,19.0
4,2026-01-06,Nightjet,NS Int,402,False,False,0,08:52,22.0,False,08:55,22.0,False,False,14.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,2026-01-06,Intercity,NS,302985,False,True,0,23:06,0.0,False,23:09,0.0,False,False,18.0,18.0
1415,2026-01-06,Intercity,NS,302987,False,True,0,23:36,0.0,False,23:39,0.0,False,False,18.0,18.0
1416,2026-01-06,Intercity,NS,302983,False,True,0,22:36,0.0,False,22:39,0.0,False,False,18.0,18.0
1417,2026-01-06,Intercity,NS,302989,False,True,0,00:06,2.0,False,00:09,0.0,False,False,18.0,18.0
1418,2026-01-06,Intercity,NS,300591,False,True,0,00:47,0.0,True,00:51,1.0,False,True,12.0,11.0

In [82]:
cancelled_train_dep

,Service:Date,Service:Type,Service:Company,Service:Train number,Service:Completely cancelled,Service:Partly cancelled,Service:Maximum delay,Stop:Arrival time,Stop:Arrival delay,Stop:Arrival cancelled,Stop:Departure time,Stop:Departure delay,Stop:Departure cancelled,Stop:Platform change,Stop:Planned platform,Stop:Actual platform
7,2026-01-06,Intercity,NS,1714,True,True,0,06:23,0.0,True,06:28,0.0,True,False,NaN,NaN
8,2026-01-06,Intercity,NS,3019,True,True,0,06:51,0.0,True,06:53,0.0,True,False,NaN,NaN
9,2026-01-06,Sprinter,NS,5710,False,True,0,NaN,NaN,NaN,05:07,0.0,True,False,NaN,NaN
10,2026-01-06,Intercity,NS,2919,True,True,0,06:36,0.0,True,06:39,0.0,True,False,NaN,NaN
11,2026-01-06,Sprinter,NS,6010,True,True,0,NaN,NaN,NaN,05:12,0.0,True,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1407,2026-01-06,Intercity,NS,302972,False,True,0,20:51,0.0,True,20:54,0.0,True,False,NaN,NaN
1408,2026-01-06,Intercity,NS,302976,False,True,0,21:51,0.0,True,21:54,0.0,True,False,NaN,NaN
1409,2026-01-06,Intercity,NS,302974,False,True,0,21:21,0.0,True,21:24,0.0,True,False,NaN,NaN
1410,2026-01-06,Intercity,NS,302978,False,True,0,22:21,0.0,True,22:24,0.0,True,False,NaN,NaN
1412,2026-01-06,Intercity,NS,302980,False,True,0,22:51,0.0,True,22:54,0.0,True,False,NaN,NaN

In [84]:
train_disrupted.columns

Index(['Service:Date', 'Service:Type', 'Service:Company',
       'Service:Train number', 'Service:Completely cancelled',
       'Service:Partly cancelled', 'Service:Maximum delay',
       'Stop:Arrival time', 'Stop:Arrival delay', 'Stop:Arrival cancelled',
       'Stop:Departure time', 'Stop:Departure delay',
       'Stop:Departure cancelled', 'Stop:Platform change',
       'Stop:Planned platform', 'Stop:Actual platform'],
      dtype='str')

In [85]:
weekday_counts = (
    counts_per_day
    .groupby('Weekday')['count']
    .mean()
    .reindex([
        'Monday', 'Tuesday', 'Wednesday',
        'Thursday', 'Friday', 'Saturday', 'Sunday'
    ])
)

print(f"Number of trains on a wednesday on average: {weekday_counts.iloc[2]} vs Number of trains on disrupted wednesday: {counts_per_day.loc[counts_per_day['Service:Date'] =='2026-01-06', 'count'].iloc[0]}")
print(f"Number of trains on a wednesday on average: {weekday_counts.iloc[2]} vs Number of trains on disrupted wednesday: {counts_per_day.loc[counts_per_day['Service:Date'] =='2026-01-06', 'count'].iloc[0]}")

Number of trains on a wednesday on average: 1422.75 vs Number of trains on disrupted wednesday: 1420
Number of trains on a wednesday on average: 1422.75 vs Number of trains on disrupted wednesday: 1420

In [86]:
train_intercity = train[train['Service:Type'] == 'Intercity']
train_sprinter = train[train['Service:Type'] == 'Sprinter']

train_other = train[~train['Service:Type'].isin(['Intercity', 'Sprinter'])]

#### Weather data

In [87]:
weather = pd.read_csv('weather_selected.csv')
weather.head()

,# STN,YYYYMMDD,HH,DD,FH,FF,FX,T,T10N,TD,...,VV,N,U,WW,IX,M,R,S,O,Y
0,260,20260101,1,250,40,40,90,44,NaN,10,...,50,8.0,78,NaN,NaN,0,0,0,0,0
1,260,20260101,2,240,50,50,90,45,NaN,7,...,65,8.0,76,NaN,NaN,0,0,0,0,0
2,260,20260101,3,240,50,50,100,45,NaN,5,...,80,8.0,75,NaN,NaN,0,0,0,0,0
3,260,20260101,4,240,50,50,100,43,NaN,5,...,82,8.0,76,NaN,NaN,0,0,0,0,0
4,260,20260101,5,240,60,60,110,45,NaN,4,...,82,8.0,74,NaN,NaN,0,0,0,0,0

# Data Pipeline